name: Continuous Integration by Local

on:
  push:
    branches:
      - main

jobs:
  Local_Image:
    runs-on: self-hosted 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t local_image:0.1 C:\Users\User\Desktop\Devops-Dinghy\Yakir\CI\Continuous-Integration\app

      - name: List Docker Images
        run: docker images

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: C:\Users\User\Desktop\Devops-Dinghy\Yakir\CI\Continuous-Integration\app
          push: true
          tags: |
            local_image:0.1

      - name: Logout from Docker Hub
        run: docker logout

      - name: Run Docker Container
        run: docker run -d --name local_container -p 9002:9001 local_image:0.1

      - name: List Docker Processes
        run: docker ps
