name: Continuous Integration by Local

on:
  push:
    branches:
      - main

jobs:
  Local_Image:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t local_image:0.2 ./app

      - name: List Docker Images
        run: docker images

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./app
          push: true
          tags: shiranman/continuous-integration:0.2

      - name: Build Docker Image
        run: docker build -t local_image:0.2 -f C:\Users\User\Desktop\Devops-Dinghy\Yakir\CI\Continuous-Integration\app\Dockerfile C:\Users\User\Desktop\Devops-Dinghy\Yakir\CI\Continuous-Integration\app

      - name: Run Docker Container
        run: docker run -d --name dockerhub_container -p 9000:9001 local_image:0.2
