name: Continuous Integration by Local

on:
  push:
    branches:
      - main

jobs:
  Local_Image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 #git clone

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 #download docker to the ubuntu machine

      - name: Login to Docker Hub
        uses: docker/login-action@v2 #login docker hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2 #build image + push action
        with:
          context: ./app  # Path to the Dockerfile and build context ./app file
          push: true #push to docker hub
          tags: |
            shiranman/continuous-integration:0.1.1

      - name: Logout from Docker Hub
        run: docker logout